---
title: "What does the EZfate package do?"
author: "James Pringle"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Dispersal in the global coastal ocean

Would you, without running your own regional numerical ocean circulation model or downloading terrabytes of numerical ocean circulation model output, like to:

- See where all particles that left a place in the global coastal ocean (say Portsmouth NH) and drift at the surface (or some other depth) for 30 days go? 
- Do you want to know where all particles that left from within some distance of the coast and ended up at Portsmouth NH started? 
- Do you want to know if larvae were released at Portsmouth NH, and allowed to settle in coastal habitat for 5 generations, where would they end up? Where would their density be greatest? 
- **IMPORTANT**: Right now this is in development, and the interface may change. Also, at least at first, a limited number of release depths, vertical behaviors, and, perhaps most importantly, regions will be included. Right now, data is only available for North and South America, as will be shown below. When the code is ready to released, the rest of the globe will be simulated. 

All this can be done with pre-computed particle tracks from the Mercator 1/12th of degree global ocean model, as described in [in this data sheet](https://www.mercator-ocean.eu/wp-content/uploads/2017/02/SYSTEM-sheet-_PSY4V3R1_2017.pdf). The particle tracking was made with oceanParcels, a python package described in at [oceanparcels.org](https://oceanparcels.org/). For details of dates included, depths released and depth behaviors simulated, see the current github repository at <https://github.com/JamiePringle/EZfate>.

To quickly see what you need to do generate these figures, and to adapt this resource to your needs, the following R notebooks are provided. If you want to get a quick glimpse of the capabilities of this code, you can skip ahead to notebook 04 and the following notebooks. But if you want to use this code, please go through them carefully and in order through at least notebook 6. 

- [**02_whatYouNeedToHave**](02_whatYouNeedToHave.html): Describes what needs to be configured in R before using this code. 
- [**03_getData_Subset_and_Combine**](03_GetData_Subset_and_Combine.html): How to retrive the dispersal data you need, and subsetted by space, relese time, and time drifting with the currents as appropiate to your project. 
- [**04_dataStructure_and_basicPlotting**](04_dataStructures_and_basicPlotting.html): A description of how the connectivity data is stored in R, and how to make simple plots of the dispersal data. At the end of this, you will be able to plot where particles released at a single point go, and where all the particles from an arbitrary region go. 
- [**05_connectivityModeling**](05_connectivityModeling.html): The particle fate data obtained above can be used to model the dispersal of particles over multiple releases in a defined habitat. This can be used to model connectivity of marine populations. How to define a habitat and model dispersal is described here for a simple 1 species model with no density dependence. 
- **06_backwardsInTimeModeling**: Often it will be important to understand where particles which have arrived at a specific place came from. This describes how to start doing this. *This has not yet been finished*

To download the code to run it locally, go to the [gitHub directiory](https://github.com/JamiePringle/EZfate) and look at the right-hand side toolbar for the "Releases" tab and click on the green "latest" button, or go [to this page.](https://github.com/JamiePringle/EZfate/releases/)

**In the next section, you will learn what R packages must be installed to use EZfate.**
